// <auto-generated />
using System;
using CollabSphere.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollabSphere.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122113733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollabSphere.API.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily standup meeting",
                            EndTime = new DateTime(2026, 1, 22, 20, 37, 32, 833, DateTimeKind.Local).AddTicks(5496),
                            IsActive = true,
                            Participants = "",
                            StartTime = new DateTime(2026, 1, 22, 19, 37, 32, 833, DateTimeKind.Local).AddTicks(5482),
                            Status = "Scheduled",
                            TeamName = "Development Team",
                            Title = "Team Standup"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Weekly project review",
                            EndTime = new DateTime(2026, 1, 22, 22, 37, 32, 833, DateTimeKind.Local).AddTicks(5499),
                            IsActive = true,
                            Participants = "",
                            StartTime = new DateTime(2026, 1, 22, 21, 37, 32, 833, DateTimeKind.Local).AddTicks(5499),
                            Status = "Scheduled",
                            TeamName = "Project Management",
                            Title = "Project Review"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
