// <auto-generated />
<<<<<<<< HEAD:Services/SubjectService/Migrations/20260201163411_InitialCreate.Designer.cs
========
using System;
using AuthService.Data;
>>>>>>>> 91a1422099f03fa6158355f00016af5da2dff915:Backend/Services/AuthService/Migrations/20260130103816_InitAuthDb.Designer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectService.Data;

#nullable disable

<<<<<<<< HEAD:Services/SubjectService/Migrations/20260201163411_InitialCreate.Designer.cs
namespace SubjectService.Migrations
{
    [DbContext(typeof(SubjectDbContext))]
    [Migration("20260201163411_InitialCreate")]
    partial class InitialCreate
========
namespace AuthService.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260130103816_InitAuthDb")]
    partial class InitAuthDb
>>>>>>>> 91a1422099f03fa6158355f00016af5da2dff915:Backend/Services/AuthService/Migrations/20260130103816_InitAuthDb.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:Services/SubjectService/Migrations/20260201163411_InitialCreate.Designer.cs
            modelBuilder.Entity("SubjectService.Models.Subject", b =>
========
            modelBuilder.Entity("AuthService.Models.User", b =>
>>>>>>>> 91a1422099f03fa6158355f00016af5da2dff915:Backend/Services/AuthService/Migrations/20260130103816_InitAuthDb.Designer.cs
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<<< HEAD:Services/SubjectService/Migrations/20260201163411_InitialCreate.Designer.cs
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
========
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");
>>>>>>>> 91a1422099f03fa6158355f00016af5da2dff915:Backend/Services/AuthService/Migrations/20260130103816_InitAuthDb.Designer.cs

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:Services/SubjectService/Migrations/20260201163411_InitialCreate.Designer.cs
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");
>>>>>>>> 91a1422099f03fa6158355f00016af5da2dff915:Backend/Services/AuthService/Migrations/20260130103816_InitAuthDb.Designer.cs

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
